development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: gtakeda
  password: "123"

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: gtakeda
  password: "123"

production:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: gtakeda
  password: "123"
